apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chat-with-epi.fullname" . }}
  labels:
    {{- include "chat-with-epi.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPENAI_KEY: {{ .Values.secret.openaiKey | quote }}
