apiVersion: v1
kind: Service
metadata:
  name: {{ include "chat-with-epi.fullname" . }}
  labels:
    {{- include "chat-with-epi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "chat-with-epi.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
